IMAGES_DIR: '/home/dsi/shaya/chexpert_v1_small/CheXpert-v1.0-small/'
RES_DIR: '/home/dsi/shaya/ct_data/res/'

BATCH_SIZE: 16


ENCODER_NAME: "densenet121"
ENCODER_DEPTH: 5
ENCODER_WEIGHTS: "/home/dsi/shaya/exp/medical.pt"
N_CHANNELS: 3
NUM_CLASSES: 5
NUM_EPOCHS: 5
LR: 0.0001
LR_DECAY_STEP_SIZE: 1
GAMMA_DECAY: 0.6
DS_CREATOR: "chexpert_ds_creator"

FRONT_OR_LAT: "FRONT"
AVG: False
AVG_PARAMS: False
CONCAT: False
SOFT_FREEZE: False
USE_REGULARIZED_LOSS: False
FINE_REGULARIZED_LOSS: False
ALPHA: 4
LAYER_WISE: False
ONLY_MIDDLE: False
LEARN_AVG: False
LR_FOR_MIDDLE_LAYER: 0.01
BEST_MODEL_PATH: ""